### PR TITLE
Optimize for timer timeout extension

### PR DESCRIPTION
**Pull request by cmeissl**

### CODE REVIEW

**Comment by notgull** [comment]
@cmeissl The CI issues are fixed on master, please rebase

**Comment by notgull** [comment]
@cmeissl try again

**Comment by cmeissl** [comment]
> @cmeissl try again

The CI failed because the version (latest) of `criterion` depends on `clap` which requires a newer MSRV. I downgraded `criterion` for now, but maybe it would also be an option to split the tests and the MSRV checks in the future.

**Comment by cmeissl** [comment]
@notgull I had to downgrade a few other deps, but the CI is now green finally!

**Review by notgull — APPROVED** [review]
Thanks!

**Pull request merged**
