### PR TITLE
chore: use tracing instead of log crate

### PR DESCRIPTION
**Pull request by joshka**
Fixes: https://github.com/Smithay/calloop/issues/194

### CODE REVIEW

**Comment by joshka** [comment]
Tracing logs for a sample app that hits these - 
image

**Review by notgull — COMMENTED** [review]
My only hesitancy is for the long-term maintenance of the tracing crate. I know that there was a period where tracing was effectively unmaintained. Looking at the repo it looks like it's maintained better now, but I'm just worried about needing to rollback to `log` if trading ever becomes unmaintained again.

Looks good to me otherwise.

**Comment by joshka** [comment]
Fixed a log::warn that I'd missed. The CI still breaks due to the log downgrade. The MSRV of the current version of log (1.60.0) seems to be lower than calloop's MSRV (1.63.0). Does this mean that this is not necessary any more?

> My only hesitancy is for the long-term maintenance of the tracing crate. I know that there was a period where tracing was effectively unmaintained. Looking at the repo it looks like it's maintained better now, but I'm just worried about needing to rollback to `log` if trading ever becomes unmaintained again.

The other thing I noted (in #194 in case you missed it) is that this brings back in the proc-macro2 and syn crates to the dependency list (which I saw you were trying to remove by avoiding `thiserror`).

**Comment by notgull** [comment]
> The CI still breaks due to the log downgrade. The MSRV of the current version of log (1.60.0) seems to be lower than calloop's MSRV (1.63.0). Does this mean that this is not necessary any more?

Yes, it's probably not necessary.

> The other thing I noted (in #194 in case you missed it) is that this brings back in the proc-macro2 and syn crates to the dependency list (which I saw you were trying to remove by avoiding `thiserror`).

If you import tracing without default features it doesn't have these dependencies though, right?

**Comment by joshka** [comment]
> If you import tracing without default features it doesn't have these dependencies though, right?

Actually yep, you're right - I must have checked before I added that

```
calloop v0.14.0 (/Users/joshka/local/calloop)
├── bitflags v2.5.0
├── polling v3.7.2
│   ├── cfg-if v1.0.0
│   ├── rustix v0.38.34
│   │   ├── bitflags v2.5.0
│   │   ├── errno v0.3.9
│   │   │   └── libc v0.2.155
│   │   └── libc v0.2.155
│   └── tracing v0.1.40
│       ├── log v0.4.21
│       ├── pin-project-lite v0.2.14
│       └── tracing-core v0.1.32
├── rustix v0.38.34 (*)
├── slab v0.4.9
│   [build-dependencies]
│   └── autocfg v1.3.0
└── tracing v0.1.40 (*)
```

**Comment by notgull** [comment]
Please rebase on `master` to fix the CI issues. Then we should be good to go.

**Comment by joshka** [comment]
> Please rebase on `master` to fix the CI issues. Then we should be good to go.

Done

**Review by notgull — APPROVED** [review]
Thanks!

**Pull request merged**
